# Generated by Django 3.0 on 2024-11-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_copy_lettings_and_addresses_in_new_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
