# Generated by Django 3.0 on 2024-11-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_remove_reverse_accessors_for_refactoring'),
        ('profiles', '0002_copy_profiles_in_new_table'),
        ('lettings', '0002_copy_lettings_and_addresses_in_new_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
